services:
  network-monitor:
    build: .
    ports:
      - "5000:5000" # Flask backend
      - "8501:8501" # Streamlit frontend
    volumes:
      - .:/app
      - ./db:/app/db # Mount the db folder specifically
    environment:
      - FLASK_ENV=development
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_HEADLESS=true

volumes:
  db_data:
